[input]
folder =  "E:\\Programs\\Mmed\\_Image\\Fooocus_win64_2-0-50\\Fooocus\\outputs\\2024-01-04\\"
source = "fooocus"

[output]
folder = "E:/Dropbox/Biz/_Inbox/tagging"

[db]
file = "py_digitalart_tags.db"


[app]
image_file_extensions = [".png", ".jpg", ".svg", ".jpeg"]
file_tags = ['up2_up2_up2', 'up2_up2', 'up2', 'orig', 'up4', 'up6', 'v2', 'v3']


[ai]
api_pasue = 3
