[input]
# folder =  "E:\\Programs\\Mmed\\_Image\\Fooocus_win64_2-0-50\\Fooocus\\outputs\\2024-03-12\\Set1\\"
# folder =  "E:\\Programs\\Mmed\\_Image\\Fooocus_win64_2-0-50\\Fooocus\\outputs\\2024-03-23\\Set1\\"
# folder =  "E:\\Programs\\Mmed\\_Image\\Fooocus_win64_2-0-50\\Fooocus\\outputs\\2024-03-27\\"
folder =  "E:\\Programs\\Mmed\\_Image\\Fooocus_win64_2-0-50\\Fooocus\\outputs\\2024-03-16\\"
source = "fooocus"

[output]
folder = "E:/Dropbox/Biz/_Inbox/tagging"

[db]
file = "py_digitalart_tags.db"


[app]
image_file_extensions = [".png", ".jpg", ".svg", ".jpeg"]
file_tags = ['up2_up2_up2', 'up2_up2', 'up2', 'orig', 'up4', 'up6', 'v1', 'v4', 'v2', 'v3']


[ai]
api_pause = 1
model = "claude-3-haiku-20240307"
system_msg_file = ""

[upscale]
exe = "E:\\Programs\\Mmed\\_Image\\RealEsrgan-ncnn-vulkan\\realesrgan-ncnn-vulkan.exe"
scale = 4